"""
Integration test for the full pipeline.
Uses the synthetic PDF + voter roll generated by generate_test_data.py.
Skips if fixtures don't exist yet.
"""
import json
import pytest
from pathlib import Path
from shutil import which

FIXTURES = Path(__file__).parent / "fixtures"
VOTER_ROLL = FIXTURES / "voter_roll.csv"
SAMPLE_PDF = FIXTURES / "sample_petition.pdf"


@pytest.mark.skipif(
    not (VOTER_ROLL.exists() and SAMPLE_PDF.exists() and which("pdfinfo")),
    reason="Run tests/fixtures/generate_test_data.py and install poppler/pdfinfo first",
)
def test_pipeline_runs():
    from petition_verifier.pipeline import Pipeline

    pipeline = Pipeline(voter_roll_csv=VOTER_ROLL)
    result   = pipeline.process(SAMPLE_PDF, project_id="test-001")

    assert result.total_lines > 0, "No signatures extracted"
    assert result.approved + result.review + result.rejected + result.duplicates == result.total_lines

    # Sanity: at least some lines should match (synthetic data has real voter names)
    auto_rate = result.approved / result.total_lines
    assert auto_rate >= 0.30, f"Auto-approve rate too low: {auto_rate:.0%}"

    # All results should have a status
    for sig in result.signatures:
        assert sig.status is not None

    # JSON serializable
    data = json.loads(result.model_dump_json())
    assert data["project_id"] == "test-001"


def test_high_confidence_match_without_signature_needs_review():
    from petition_verifier.models import ExtractedSignature, VoterMatch, VerificationStatus
    from petition_verifier.pipeline import Pipeline

    class FakeProcessor:
        def extract(self, _path):
            return [
                ExtractedSignature(
                    line_number=1,
                    page=1,
                    raw_name="Jane Smith",
                    raw_address="123 Main St",
                    signature_present=False,
                )
            ]

    class FakeMatcher:
        def match(self, _normalized):
            return VoterMatch(
                voter_id="V001",
                voter_name="Jane Smith",
                voter_address="123 Main St",
                confidence=99,
                name_score=100,
                address_score=98,
            )

    pipeline = Pipeline.__new__(Pipeline)
    pipeline._processor = FakeProcessor()
    pipeline._matcher = FakeMatcher()

    result = pipeline.process("petition.pdf", project_id="test-missing-signature")

    assert result.approved == 0
    assert result.review == 1
    assert result.signatures[0].status == VerificationStatus.REVIEW


def test_review_packet_low_confidence_fields_fall_back_from_row_confidence(monkeypatch):
    from petition_verifier.models import ExtractedSignature
    from petition_verifier.routes.review_routes import _low_confidence_fields_for_sig

    monkeypatch.setenv("OCR_CONFIDENCE_THRESHOLD", "0.85")

    low = ExtractedSignature(
        line_number=1,
        page=1,
        raw_name="Reggie Ellison",
        raw_address="123 Main St",
        signature_present=True,
        ocr_confidence=0.5,
    )
    high = ExtractedSignature(
        line_number=2,
        page=1,
        raw_name="Jaime D Wone",
        raw_address="456 Oak St",
        signature_present=True,
        ocr_confidence=92,
    )
    explicit = ExtractedSignature(
        line_number=3,
        page=1,
        raw_name="Pat Lee",
        raw_address="789 Pine St",
        signature_present=True,
        ocr_confidence=0.99,
        low_confidence_fields=["print_name", "zip"],
    )

    assert _low_confidence_fields_for_sig(low) == ["name", "address"]
    assert _low_confidence_fields_for_sig(high) == []
    assert _low_confidence_fields_for_sig(explicit) == ["name", "address"]


def test_consensus_pipeline_marks_disagreed_fields_low_confidence(tmp_path):
    from PIL import Image

    from petition_verifier.models import ExtractedSignature
    from petition_verifier.routes.review_routes import _apply_consensus_to_signatures

    crop_path = tmp_path / "row-1.jpg"
    Image.new("RGB", (240, 60), "white").save(crop_path)
    sig = ExtractedSignature(
        line_number=1,
        page=1,
        raw_name="Boyce Shelton",
        raw_address="123 Oak Ave",
        signature_present=True,
        ocr_confidence=0.95,
    )

    def fake_extractor(_crop, county=""):
        return {
            "consensus": {
                "name": "",
                "address": "123 Oak Ave",
                "city": "Pasadena",
                "zip_code": "91101",
                "unreliable_fields": ["name"],
            },
            "unreliable_fields": ["name"],
        }

    _apply_consensus_to_signatures([sig], {1: str(crop_path)}, extractor=fake_extractor)

    assert sig.raw_name == "Boyce Shelton"
    assert sig.raw_address == "123 Oak Ave, Pasadena, 91101"
    assert sig.low_confidence_fields == ["name"]


def test_consensus_pipeline_fails_closed_when_crop_missing():
    from petition_verifier.models import ExtractedSignature
    from petition_verifier.routes.review_routes import _apply_consensus_to_signatures

    sig = ExtractedSignature(
        line_number=1,
        page=1,
        raw_name="Reggie Ellison",
        raw_address="123 Oak Ave",
        signature_present=True,
        ocr_confidence=0.95,
    )

    _apply_consensus_to_signatures([sig], {}, extractor=lambda *_args, **_kwargs: {})

    assert sig.low_confidence_fields == ["name", "address"]
