"""
Integration test for the full pipeline.
Uses the synthetic PDF + voter roll generated by generate_test_data.py.
Skips if fixtures don't exist yet.
"""
import json
import pytest
from pathlib import Path

FIXTURES = Path(__file__).parent / "fixtures"
VOTER_ROLL = FIXTURES / "voter_roll.csv"
SAMPLE_PDF = FIXTURES / "sample_petition.pdf"


@pytest.mark.skipif(
    not (VOTER_ROLL.exists() and SAMPLE_PDF.exists()),
    reason="Run tests/fixtures/generate_test_data.py first to create fixtures",
)
def test_pipeline_runs():
    from petition_verifier.pipeline import Pipeline

    pipeline = Pipeline(voter_roll_csv=VOTER_ROLL)
    result   = pipeline.process(SAMPLE_PDF, project_id="test-001")

    assert result.total_lines > 0, "No signatures extracted"
    assert result.approved + result.review + result.rejected + result.duplicates == result.total_lines

    # Sanity: at least some lines should match (synthetic data has real voter names)
    auto_rate = result.approved / result.total_lines
    assert auto_rate >= 0.30, f"Auto-approve rate too low: {auto_rate:.0%}"

    # All results should have a status
    for sig in result.signatures:
        assert sig.status is not None

    # JSON serializable
    data = json.loads(result.model_dump_json())
    assert data["project_id"] == "test-001"
