"""initial schema

Revision ID: 494cd34bb43d
Revises: 
Create Date: 2026-05-14 12:05:25.539295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '494cd34bb43d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pay_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('review', sa.Integer(), nullable=True),
    sa.Column('rejected', sa.Integer(), nullable=True),
    sa.Column('duplicates', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('fraud_flagged_lines', sa.Integer(), nullable=True),
    sa.Column('fraud_flags_json', sa.Text(), nullable=True),
    sa.Column('continuation_of', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['continuation_of'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hourly_wage', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key(
            'fk_teams_manager_id_users',
            'teams',
            'users',
            ['manager_id'],
            ['id'],
        )
    op.create_table('live_sig_counts',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('sig_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('payment_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('pay_period_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('total_signatures', sa.Integer(), nullable=True),
    sa.Column('valid_signatures', sa.Integer(), nullable=True),
    sa.Column('validity_rate', sa.Float(), nullable=True),
    sa.Column('hourly_wage_used', sa.Float(), nullable=True),
    sa.Column('base_pay_cents', sa.Integer(), nullable=True),
    sa.Column('bonus_cents', sa.Integer(), nullable=True),
    sa.Column('gross_cents', sa.Integer(), nullable=True),
    sa.Column('tax_cents', sa.Integer(), nullable=True),
    sa.Column('net_cents', sa.Integer(), nullable=True),
    sa.Column('earns_lunch', sa.Boolean(), nullable=True),
    sa.Column('breakdown_json', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('raw_path', sa.String(), nullable=True),
    sa.Column('cleaned_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('page_fingerprint', sa.String(), nullable=True),
    sa.Column('new_sigs', sa.Integer(), nullable=True),
    sa.Column('already_counted', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('voter_roll_text', sa.Text(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.String(), nullable=False),
    sa.Column('preferred_days', sa.Text(), nullable=True),
    sa.Column('preferred_hours', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('raw_address', sa.String(), nullable=True),
    sa.Column('raw_date', sa.String(), nullable=True),
    sa.Column('signature_present', sa.Boolean(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('voter_id', sa.String(), nullable=True),
    sa.Column('voter_name', sa.String(), nullable=True),
    sa.Column('voter_address', sa.String(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('name_score', sa.Float(), nullable=True),
    sa.Column('address_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duplicate_of_line', sa.Integer(), nullable=True),
    sa.Column('staff_override', sa.String(), nullable=True),
    sa.Column('staff_voter_id', sa.String(), nullable=True),
    sa.Column('staff_notes', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'line_number', name='uq_signatures_project_line')
    )
    op.create_table('worker_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('manual_sig_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_packet_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('row_fingerprint', sa.String(), nullable=True),
    sa.Column('row_status', sa.String(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('norm_name', sa.String(), nullable=True),
    sa.Column('raw_address', sa.String(), nullable=True),
    sa.Column('norm_address', sa.String(), nullable=True),
    sa.Column('raw_city', sa.String(), nullable=True),
    sa.Column('raw_zip', sa.String(), nullable=True),
    sa.Column('valid_zip', sa.Boolean(), nullable=True),
    sa.Column('raw_date', sa.String(), nullable=True),
    sa.Column('has_signature', sa.Boolean(), nullable=True),
    sa.Column('ai_verdict', sa.String(), nullable=True),
    sa.Column('ai_reason', sa.String(), nullable=True),
    sa.Column('flags_json', sa.Text(), nullable=True),
    sa.Column('voter_status', sa.String(), nullable=True),
    sa.Column('voter_confidence', sa.Integer(), nullable=True),
    sa.Column('voter_reason', sa.String(), nullable=True),
    sa.Column('fraud_flags', sa.Text(), nullable=True),
    sa.Column('fraud_score', sa.Integer(), nullable=True),
    sa.Column('review_decision', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['packet_id'], ['review_packets.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packet_id', 'line_no', name='uq_review_packet_lines_packet_line')
    )
    op.create_table('shift_reflections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('sigs_reported', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('hit_goal', sa.Boolean(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint('fk_teams_manager_id_users', 'teams', type_='foreignkey')
    op.drop_table('shift_reflections')
    op.drop_table('review_packet_lines')
    op.drop_table('worker_projects')
    op.drop_table('worker_locations')
    op.drop_table('signatures')
    op.drop_table('shifts')
    op.drop_table('schedule_requests')
    op.drop_table('review_packets')
    op.drop_table('payroll_records')
    op.drop_table('payment_preferences')
    op.drop_table('live_sig_counts')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('projects')
    op.drop_table('pay_periods')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
